### ISSUE TITLE
Errors when running the project

### ISSUE THREAD

**Issue by mschuh** [openshim/shim2#1]
Following the instructions in `docs/README.pdf` I run into errors when running the project as an *Eclipse Application* or when selecting the *Run Configuration* and then validating the plug-ins.

## Expected Behavior
When running the project I should have a window displayed with the *ShimEdit* title and no errors.

## Current Behavior
When I try to just run the project as an application, Eclipse warns me that there are errors in required projects and asks for confirmation to launch. If I choose to proceed a window appears showing the detected problems:

```
-> org.multicore-association.shim.edit
   -> Missing Constraint: Require-Bundle: org.apache.commons.lang3; bundle-version="3.1.0"
   -> Missing Constraint: Require-Bundle: org.eclipse.emf.ecp.edit; bundle-version="[1.21.0,1.22.0)"
   -> Missing Constraint: Require-Bundle: org.eclipse.emf.ecp.ui; bundle-version="1.21.0"
   -> Missing Constraint: Require-Bundle: org.eclipse.emf.ecp.ui.view, bundle-version="[1.21.0,1.22.0)"
   -> Missing Constraint: Require-Bundle: org.eclipse.emf. ecp.validation; bundle-version="1.21.0"
```

If I choose to continue nonetheless I receive an error dialog saying that the application could not start. The complete log is available here [shim-log.txt](https://github.com/openshim/shim2/files/6048722/shim-log.txt)

Going into *Run Configurations...* and then the *Plug-ins* tab, clicking on *Add Required Plug-ins* does increase the number of selected plugins but then clicking on *Validate Plug-ins* shows the same missing constraint errors as above.

## Possible Solution
Maybe manually installing the bundles that are missing. I have found the first one [here](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3) but I did not try to install it as Eclipse should have a better way to retrieve this automatically that I am not aware of.

## Context (Environment)
- OS: Manjaro Linux x86_64
- Kernel: 5.9.16-1-MANJARO
- JDK15
- Eclipse IDE 2020-12

**Comment by ketayan** [comment]
There is a possibility of an error due to a different version of Eclipse. Currently, the operation can be verified only with the Eclipse version described in the [docs/README.pdf](https://github.com/openshim/shim2/blob/master/docs/README.md) .
So, could you please try again with the version of eclipse described in the README？

**Comment by mschuh** [comment]
I have reinstalled the Modeling Tools from Eclipse 2019-06 and I can confirm that after clicking on *Add Required Plug-ins* in the *Run Configurations...* window, the *ShimEdit* software launches successfully. I will play around with some models now and if I find any other problems I will open another issue.
Thanks for your help.
