### ISSUE TITLE
UML diagrams

### ISSUE THREAD

**Issue by fxf06** [openshim/shim2#3]
Hello openshim,

Would it be possible to have also the project (I guess EA) that has been used for the UML classes in the standard?
It could be delivered with the .xsd.

Thanks!

**Comment by fujim2** [comment]
> Would it be possible to have also the project (I guess EA) that has been used for the UML classes in the standard?
> It could be delivered with the .xsd.
Hello, 

The xsd file of SHIM2.0 can be found below.
https://github.com/openshim/shim2/tree/master/schema

If you have EA, you can make UML by importing this xsd file?
https://sparxsystems.com/enterprise_architect_user_guide/15.2/model_domains/import_xsd.html

Thanks.
